#!/usr/bin/env python

import re
import sys

_, input = sys.argv
output = input.replace(".tex", ".new.tex")

def save(new):
    with file(output, 'w') as f:
        f.write(new)

save(re.sub(r'"{}(.*?)"{}', r"``\1''", file(input).read(), 0, re.DOTALL))
