#!/usr/bin/env python

import re

input = "theego.tex"
output = "output.tex"

def save(new):
    with file(output, 'w') as f:
        f.write(new)

save(re.sub(r'"{}(.*?)"{}', r"``\1''", file(input).read(), 0, re.DOTALL))
